name = "compass-ts"
main = "src/workers/search.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[vectorize]]
binding = "VECTORIZE"
index_name = "documentation"

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "fa3dc6c06433f6b0ea78d95bce23ad91"
CLOUDFLARE_API_TOKEN = "fTmZjFFCGuhUppQ0XOScPWPIl8hJnqSLl4tpf_Jf"

[[d1_databases]]
binding = "SUPPORT_DB"
database_name = "support"
database_id = "e2d54e53-bad8-4927-9ed7-d401d5488c6a"

pages_build_output_dir = "out"