name = "compass-ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Specify the build output directory for Pages
pages_build_output_dir = "out" 